site:
  name: Pozytywnie Zbudowani
  site: 'https://pozytywniezbudowani.pl'
  base: '/'
  trailingSlash: true

  googleSiteVerificationId: w15b1kbUK2vfeH2RhSRiOll1VLMzhQp225mvpLChWWI

# Default SEO metadata
metadata:
  title:
    default: Pozytywnie Zbudowani — Wojciech Tracichleb
    template: '%s — Pozytywnie Zbudowani'
  description: "Budowa domu jednorodzinnego krok po kroku | Od Marzenia Do Wprowadzenia Wojciech Tracichleb | Kompleksowy poradnik budowy domu | Sprawdź teraz!"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Pozytywnie Zbudowani
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@pozytywniezbudowani'
    site: '@pozytywniezbudowani'
    cardType: summary_large_image

i18n:
  language: pl
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 12

    post:
      isEnabled: true
      permalink: '/blog/%slug%/'
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog'
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category'
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag'
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 3

analytics:
  vendors:
    googleAnalytics:
      id: null # GTM-PKRLVW2G will be added via Partytown in layout

ui:
  theme: 'system'
